Lname = input('What is your last name?\n')
FName = input ('what is your First name?\n')
DateOfBirth = input ('Enter your date of birth\n')
Gender = input ('what is your gender\n')
County = input ('are you are resident of pierce county?\n')
Provider = input ('Do you have provider one verified?\n')
Phone = input('what is your phone number?\n')
Substance= input('what would you want to detox from?\n')
print ('Your Details are', Lname, FName, DateOfBirth,Gender,County, Provider,Phone,Substance)
